package com.fruitshop.user.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-03T09:57:11.636+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.user.com/", name = "UserServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceInterface {

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://service.user.com/", className = "com.fruitshop.user.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.user.com/", className = "com.fruitshop.user.service.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.fruitshop.user.service.User login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://service.user.com/", className = "com.fruitshop.user.service.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://service.user.com/", className = "com.fruitshop.user.service.RegistResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean regist(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fruitshop.user.service.User arg0
    );
}
