package com.fruit.service2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-05T10:30:53.622+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.fruit.com/", name = "FruitServiceInterface2")
@XmlSeeAlso({ObjectFactory.class})
public interface FruitServiceInterface2 {

    @WebMethod
    @RequestWrapper(localName = "updateReserve", targetNamespace = "http://service.fruit.com/", className = "com.fruit.service2.UpdateReserve")
    @ResponseWrapper(localName = "updateReserveResponse", targetNamespace = "http://service.fruit.com/", className = "com.fruit.service2.UpdateReserveResponse")
    public void updateReserve(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.fruit.service2.UpdateEntry> arg0
    ) throws Exception_Exception;
}
