package com.fruit.service2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-05T10:30:53.634+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "FruitServiceInterface2Service",
                  wsdlLocation = "http://127.0.0.1:8084/ws-fruitshop-fruit/ws/fruit2?wsdl",
                  targetNamespace = "http://service.fruit.com/")
public class FruitServiceInterface2Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.fruit.com/", "FruitServiceInterface2Service");
    public final static QName FruitServiceInterface2Port = new QName("http://service.fruit.com/", "FruitServiceInterface2Port");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8084/ws-fruitshop-fruit/ws/fruit2?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FruitServiceInterface2Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8084/ws-fruitshop-fruit/ws/fruit2?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FruitServiceInterface2Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FruitServiceInterface2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FruitServiceInterface2Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FruitServiceInterface2Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FruitServiceInterface2Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FruitServiceInterface2Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FruitServiceInterface2
     */
    @WebEndpoint(name = "FruitServiceInterface2Port")
    public FruitServiceInterface2 getFruitServiceInterface2Port() {
        return super.getPort(FruitServiceInterface2Port, FruitServiceInterface2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FruitServiceInterface2
     */
    @WebEndpoint(name = "FruitServiceInterface2Port")
    public FruitServiceInterface2 getFruitServiceInterface2Port(WebServiceFeature... features) {
        return super.getPort(FruitServiceInterface2Port, FruitServiceInterface2.class, features);
    }

}
