package com.fruitshop.order.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-05T10:59:37.694+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.order.com/", name = "OrderServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderServiceInterface {

    @WebMethod
    @RequestWrapper(localName = "findOrderByUserID", targetNamespace = "http://service.order.com/", className = "com.fruitshop.order.service.FindOrderByUserID")
    @ResponseWrapper(localName = "findOrderByUserIDResponse", targetNamespace = "http://service.order.com/", className = "com.fruitshop.order.service.FindOrderByUserIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.fruitshop.order.service.Order> findOrderByUserID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://service.order.com/", className = "com.fruitshop.order.service.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://service.order.com/", className = "com.fruitshop.order.service.AddOrderResponse")
    public void addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.fruitshop.order.service.Order arg0
    ) throws Exception_Exception;
}
