package com.fruitshop.order.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-05T10:59:37.710+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "OrderServiceInterfaceService",
                  wsdlLocation = "http://127.0.0.1:8087/ws-fruitshop-order/ws/order?wsdl",
                  targetNamespace = "http://service.order.com/")
public class OrderServiceInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.order.com/", "OrderServiceInterfaceService");
    public final static QName OrderServiceInterfacePort = new QName("http://service.order.com/", "OrderServiceInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8087/ws-fruitshop-order/ws/order?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderServiceInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8087/ws-fruitshop-order/ws/order?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderServiceInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderServiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderServiceInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrderServiceInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderServiceInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderServiceInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrderServiceInterface
     */
    @WebEndpoint(name = "OrderServiceInterfacePort")
    public OrderServiceInterface getOrderServiceInterfacePort() {
        return super.getPort(OrderServiceInterfacePort, OrderServiceInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderServiceInterface
     */
    @WebEndpoint(name = "OrderServiceInterfacePort")
    public OrderServiceInterface getOrderServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(OrderServiceInterfacePort, OrderServiceInterface.class, features);
    }

}
