package com.fruitshop.fruit.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-03T23:49:10.845+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.fruit.com/", name = "FruitServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface FruitServiceInterface {

    @WebMethod
    @RequestWrapper(localName = "findFruitPage", targetNamespace = "http://service.fruit.com/", className = "com.fruitshop.fruit.service.FindFruitPage")
    @ResponseWrapper(localName = "findFruitPageResponse", targetNamespace = "http://service.fruit.com/", className = "com.fruitshop.fruit.service.FindFruitPageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.fruitshop.fruit.service.FruitPageBean findFruitPage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "findFruitByID", targetNamespace = "http://service.fruit.com/", className = "com.fruitshop.fruit.service.FindFruitByID")
    @ResponseWrapper(localName = "findFruitByIDResponse", targetNamespace = "http://service.fruit.com/", className = "com.fruitshop.fruit.service.FindFruitByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.fruitshop.fruit.service.Fruit findFruitByID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws Exception_Exception;
}
