package com.fruitshop.fruit.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-03T23:49:10.861+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "FruitServiceInterfaceService",
                  wsdlLocation = "http://127.0.0.1:8084/ws-fruitshop-fruit/ws/fruit?wsdl",
                  targetNamespace = "http://service.fruit.com/")
public class FruitServiceInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.fruit.com/", "FruitServiceInterfaceService");
    public final static QName FruitServiceInterfacePort = new QName("http://service.fruit.com/", "FruitServiceInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8084/ws-fruitshop-fruit/ws/fruit?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FruitServiceInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8084/ws-fruitshop-fruit/ws/fruit?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FruitServiceInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FruitServiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FruitServiceInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FruitServiceInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FruitServiceInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FruitServiceInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FruitServiceInterface
     */
    @WebEndpoint(name = "FruitServiceInterfacePort")
    public FruitServiceInterface getFruitServiceInterfacePort() {
        return super.getPort(FruitServiceInterfacePort, FruitServiceInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FruitServiceInterface
     */
    @WebEndpoint(name = "FruitServiceInterfacePort")
    public FruitServiceInterface getFruitServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(FruitServiceInterfacePort, FruitServiceInterface.class, features);
    }

}
